permalink:           pretty
relative_permalinks: true
# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
highlighter:		rogue

title:               'S0lver thoughts'
tagline:             'not fantastic toughts really'
description:         'My blog site'
url:                 http://s0lver.github.io
#url:                 http://www.tamps.cinvestav.mx/~rperez/blog
baseurl:             ''
#baseurl:             'http://www.tamps.cinvestav.mx/~rperez'

gems:
- jemoji
